'use strict';
const $=(id)=>document.getElementById(id);const state={path:'',connected:false,settings:null};let timer;
function message(error){return String(error?.message||error||'操作失败').replace(/^Error invoking remote method '[^']+':\s*(?:[A-Za-z]*Error:\s*)?/,'');}
function toast(text,error=false){$('toast').textContent=text;$('toast').className=`toast show${error?' error':''}`;clearTimeout(timer);timer=setTimeout(()=>$('toast').className='toast',3000);}
function connected(value,name){state.connected=value;$('dot').classList.toggle('online',value);$('repoLabel').textContent=name||state.settings?.repository||'尚未连接';$('refresh').disabled=!value;}
function view(name){$('filesView').classList.toggle('hidden',name!=='files');$('settingsView').classList.toggle('hidden',name!=='settings');$('filesNav').classList.toggle('active',name==='files');$('settingsNav').classList.toggle('active',name==='settings');}
function size(bytes){if(!bytes)return'—';const units=['B','KB','MB','GB'];const i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),3);return`${(bytes/1024**i).toFixed(i?1:0)} ${units[i]}`;}
function crumbs(){const parts=state.path?state.path.split('/'):[];const el=$('breadcrumbs');el.replaceChildren();const root=document.createElement('button');root.textContent='根目录';root.onclick=()=>navigate('');el.append(root);parts.forEach((part,index)=>{el.append(document.createTextNode(' › '));const button=document.createElement('button');button.textContent=part;if(index<parts.length-1)button.onclick=()=>navigate(parts.slice(0,index+1).join('/'));el.append(button);});}
function rows(items){$('list').replaceChildren();$('empty').classList.toggle('hidden',items.length||state.connected);if(!items.length&&state.connected){const empty=document.createElement('div');empty.className='empty';empty.textContent='这个文件夹是空的';$('list').append(empty);}for(const item of items){const row=document.createElement('div');row.className='item';const name=document.createElement('span');name.className='name';name.textContent=`${item.type==='dir'?'▰':'▤'}  ${item.name}`;if(item.type==='dir')name.onclick=()=>navigate([state.path,item.name].filter(Boolean).join('/'));const itemSize=document.createElement('span');itemSize.textContent=item.type==='dir'?'文件夹':size(item.size);const actions=document.createElement('span');actions.className='actions';const downloadButton=document.createElement('button');downloadButton.className='download';downloadButton.textContent='下载';downloadButton.onclick=()=>download({...item,path:[state.path,item.name].filter(Boolean).join('/')});const deleteButton=document.createElement('button');deleteButton.className='delete';deleteButton.textContent='删除';deleteButton.onclick=()=>remove({...item,path:[state.path,item.name].filter(Boolean).join('/')});actions.append(downloadButton,deleteButton);row.append(name,itemSize,actions);$('list').append(row);}}
async function navigate(remotePath){state.path=remotePath;crumbs();try{rows(await window.repoDrive.list(remotePath));connected(true);}catch(error){connected(false);rows([]);toast(message(error),true);}}
async function download(item){try{$('progress').classList.remove('hidden');const result=await window.repoDrive.download(item);if(!result.canceled)toast('下载完成，已在文件管理器中显示');}catch(error){toast(message(error),true);}finally{$('progress').classList.add('hidden');}}
async function remove(item){try{const result=await window.repoDrive.delete(item);if(!result.canceled){toast(`删除完成，共删除 ${result.deleted} 个文件`);await navigate(state.path);}}catch(error){toast(message(error),true);}finally{$('progress').classList.add('hidden');}}
async function init(){const saved=await window.repoDrive.getSettings();state.settings=saved;for(const id of['repository','branch','rootPath','proxy'])$(id).value=saved[id]||'';$('clearRow').classList.toggle('hidden',!saved.hasToken);connected(false);if(saved.repository){try{const repo=await window.repoDrive.connect();connected(true,repo.fullName);await navigate('');}catch(error){toast(message(error),true);view('settings');}}}
$('filesNav').onclick=()=>view('files');$('settingsNav').onclick=()=>view('settings');$('setup').onclick=()=>view('settings');$('refresh').onclick=()=>navigate(state.path);window.repoDrive.onProgress((value)=>{$('progress').classList.remove('hidden');$('progressLabel').textContent=value.kind==='delete'?'正在删除':'正在下载';$('progressPath').textContent=value.current||'';});
$('form').onsubmit=async(event)=>{event.preventDefault();$('status').textContent='正在测试…';try{const result=await window.repoDrive.saveSettings({repository:$('repository').value,branch:$('branch').value,rootPath:$('rootPath').value,proxy:$('proxy').value,token:$('token').value,clearToken:$('clearToken').checked});state.settings=result.settings;connected(true,result.repo.fullName);$('status').textContent='连接成功';view('files');await navigate('');}catch(error){$('status').textContent='连接失败';toast(message(error),true);}};init().catch((error)=>toast(message(error),true));
